backend:
  name: github
  repo: si0rac/jekyll-doc-theme # Path to your Github repository
  branch: master

publish_mode: editorial_workflow

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "Bitrise_CLI" # Used in routes, e.g., /admin/collections/blog
    label: "Bitrise CLI" # Used in the UI
    folder: "pages/Bitrise_CLI" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "permalink", name: "permalink", widget: "string", default: "{{slug}}.html"}
      - {label: "Sidebar", name: "sidebar", widget: "string", default: "product1_sidebar"}


  - name: "bitrise_io" # Used in routes, e.g., /admin/collections/blog
    label: "Bitrise.io" # Used in the UI
    folder: "pages/Bitrise_io" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "permalink", name: "permalink", widget: "string", default: "{{slug}}.html"}
      - {label: "Sidebar", name: "sidebar", widget: "string", default: "Bitrise_io"}

  - name: "reuse" # Used in routes, e.g., /admin/collections/blog
    label: "Reuseable content" # Used in the UI
    folder: "_includes/custom" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
